# Generated by Django 4.2.7 on 2025-09-26 13:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng')),
                ('name', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã PKKH')),
                ('description', models.TextField(verbose_name='Mô tả Phân Khúc Khách hàng')),
            ],
            options={
                'verbose_name': 'Phân khúc khách hàng',
                'verbose_name_plural': 'Phân khúc khách hàng',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã đơn hàng')),
                ('created_at', models.DateTimeField(verbose_name='Thời gian tạo đơn')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Mã nhóm hàng')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm hàng')),
            ],
            options={
                'verbose_name': 'Nhóm hàng',
                'verbose_name_plural': 'Nhóm hàng',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã mặt hàng')),
                ('name', models.CharField(max_length=200, verbose_name='Tên mặt hàng')),
                ('import_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá Nhập')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.productcategory', verbose_name='Nhóm hàng')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customersegment', verbose_name='Phân khúc'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Đơn giá')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Thành tiền')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
